name: CD deploy new feature
on:
  push:
    branches: 
      - main

jobs:
  build_deploy_digitalocean:
    runs-on: ubuntu-latest    
    steps:
      - name: the deploy new feature
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: whoami